// <autogenerated>
//   This file was generated by T4 code generator Adjust.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, int idx, IList<TValue> list, string memberName) {
			return Currying.Adjust(fn, idx, list, memberName);
		}
		
		public static dynamic Adjust<TValue>(RamdaPlaceholder fn, int idx, IList<TValue> list, string memberName) {
			return Currying.Adjust(fn, idx, list, memberName); 
		}
		
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, RamdaPlaceholder idx, IList<TValue> list, string memberName) {
			return Currying.Adjust(fn, idx, list, memberName); 
		}
		
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, int idx, RamdaPlaceholder list, string memberName) {
			return Currying.Adjust(fn, idx, list, memberName); 
		}
		
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, int idx, IList<TValue> list, RamdaPlaceholder memberName = null) {
			return Currying.Adjust(fn, idx, list, memberName); 
		}
		
		
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, RamdaPlaceholder idx = null, RamdaPlaceholder list = null, RamdaPlaceholder memberName = null) {
			return Currying.Adjust(fn, idx, list, memberName);
		}
		
		
		public static dynamic Adjust<TValue>(Func<TValue, TValue> fn, int idx, RamdaPlaceholder list = null, RamdaPlaceholder memberName = null) {
			return Currying.Adjust(fn, idx, list, memberName);
		}
		
		public static dynamic Adjust<TValue>(RamdaPlaceholder fn = null, RamdaPlaceholder idx = null, RamdaPlaceholder list = null, RamdaPlaceholder memberName = null) {
			return Currying.Adjust(fn, idx, list, memberName);
		}
	}
}