// <autogenerated>
//   This file was generated by T4 code generator All.listxf.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic All<TSource>(Func<TSource, bool> fn, ITransformer list) {
			return Currying.All(Delegate(fn), list);
		}

		public static dynamic All(RamdaPlaceholder fn, ITransformer list) {
			return Currying.All(fn, list);
		}

		public static dynamic All(dynamic fn, ITransformer list) {
			return Currying.All(Delegate(fn), list);
		}
	}
}