// <autogenerated>
//   This file was generated by T4 code generator And.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic And(bool arg1, bool arg2) {
			return Currying.And(arg1, arg2);
		}
		
		public static dynamic And(RamdaPlaceholder arg1, bool arg2) {
			return Currying.And(arg1, arg2); 
		}
		
		public static dynamic And(bool arg1, RamdaPlaceholder arg2 = null) {
			return Currying.And(arg1, arg2); 
		}
		
		public static dynamic And(RamdaPlaceholder arg1 = null, RamdaPlaceholder arg2 = null) {
			return Currying.And(arg1, arg2);
		}
	}
}