// <autogenerated>
//   This file was generated by T4 code generator Ap.list.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Ap<TSource>(IList<Func<TSource, TSource>> fns, IList<TSource> vs) {
			return Currying.Ap(fns, vs);
		}

		public static dynamic Ap<TSource>(RamdaPlaceholder fns, IList<TSource> vs) {
			return Currying.Ap(fns, vs);
		}

		public static dynamic Ap<TSource>(IList<Func<TSource, TSource>> fns, RamdaPlaceholder vs = null) {
			return Currying.Ap(fns, vs);
		}

		public static dynamic Ap(RamdaPlaceholder fns = null, RamdaPlaceholder vs = null) {
			return Currying.Ap(fns, vs);
		}
	}
}