// <autogenerated>
//   This file was generated by T4 code generator Ascend.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Ascend<TSource>(Func<TSource, int> fn, TSource a, TSource b) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(RamdaPlaceholder fn, TSource a, TSource b) {
			return Currying.Ascend(fn, a, b);
		}

		public static dynamic Ascend<TSource>(Func<TSource, int> fn, RamdaPlaceholder a, TSource b) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(Func<TSource, int> fn, TSource a, RamdaPlaceholder b = null) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(Func<TSource, int> fn, RamdaPlaceholder a = null, RamdaPlaceholder b = null) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(dynamic fn, RamdaPlaceholder a, TSource b) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(dynamic fn, TSource a, RamdaPlaceholder b = null) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend(dynamic fn, RamdaPlaceholder a = null, RamdaPlaceholder b = null) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend<TSource>(dynamic fn, TSource a, TSource b) {
			return Currying.Ascend(Delegate(fn), a, b);
		}

		public static dynamic Ascend(RamdaPlaceholder fn = null, RamdaPlaceholder a = null, RamdaPlaceholder b = null) {
			return Currying.Ascend(fn, a, b);
		}
	}
}