// <autogenerated>
//   This file was generated by T4 code generator Both.delegate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Both(Delegate f, Delegate g) {
			return Currying.Both(f, g);
		}

		public static dynamic Both(RamdaPlaceholder f, Delegate g) {
			return Currying.Both(f, g);
		}

		public static dynamic Both(Delegate f, RamdaPlaceholder g = null) {
			return Currying.Both(f, g);
		}
	}
}