// <autogenerated>
//   This file was generated by T4 code generator Clamp.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Clamp(double minimum, double maximum, double value) {
			return Currying.Clamp(minimum, maximum, value);
		}
		
		public static dynamic Clamp(RamdaPlaceholder minimum, double maximum, double value) {
			return Currying.Clamp(minimum, maximum, value); 
		}
		
		public static dynamic Clamp(double minimum, RamdaPlaceholder maximum, double value) {
			return Currying.Clamp(minimum, maximum, value); 
		}
		
		public static dynamic Clamp(double minimum, double maximum, RamdaPlaceholder value = null) {
			return Currying.Clamp(minimum, maximum, value); 
		}
		
		
		public static dynamic Clamp(double minimum, RamdaPlaceholder maximum = null, RamdaPlaceholder value = null) {
			return Currying.Clamp(minimum, maximum, value);
		}
	}
}