// <autogenerated>
//   This file was generated by T4 code generator Comparator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Comparator<TArg>(Func<TArg, TArg, bool> pred) {
			return Currying.Comparator(Delegate(pred));
		}

		public static dynamic Comparator(RamdaPlaceholder pred = null) {
			return Currying.Comparator(pred);
		}

		public static dynamic Comparator(dynamic pred) {
			return Currying.Comparator(Delegate(pred));
		}
	}
}