// <autogenerated>
//   This file was generated by T4 code generator Concat.string.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Concat(string a, string b) {
			return Currying.Concat(a, b);
		}

		public static dynamic Concat(RamdaPlaceholder a, string b) {
			return Currying.Concat(a, b);
		}

		public static dynamic Concat(string a, RamdaPlaceholder b = null) {
			return Currying.Concat(a, b);
		}
	}
}