// <autogenerated>
//   This file was generated by T4 code generator ConstructN.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic ConstructN(int n, Delegate Fn) {
			return Currying.ConstructN(n, Delegate(Fn));
		}

		public static dynamic ConstructN(RamdaPlaceholder n, Delegate Fn) {
			return Currying.ConstructN(n, Delegate(Fn));
		}

		public static dynamic ConstructN(int n, RamdaPlaceholder Fn = null) {
			return Currying.ConstructN(n, Fn);
		}

		public static dynamic ConstructN(RamdaPlaceholder n, dynamic Fn) {
			return Currying.ConstructN(n, Delegate(Fn));
		}

		public static dynamic ConstructN(int n, dynamic Fn) {
			return Currying.ConstructN(n, Delegate(Fn));
		}

		public static dynamic ConstructN(RamdaPlaceholder n = null, RamdaPlaceholder Fn = null) {
			return Currying.ConstructN(n, Fn);
		}
	}
}