// <autogenerated>
//   This file was generated by T4 code generator CountBy.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic CountBy<TSource>(Func<TSource, string> fn, IList<TSource> list) {
			return Currying.CountBy(fn, list);
		}

		public static dynamic CountBy<TSource>(RamdaPlaceholder fn, IList<TSource> list) {
			return Currying.CountBy(fn, list);
		}

		public static dynamic CountBy<TSource>(Func<TSource, string> fn, RamdaPlaceholder list = null) {
			return Currying.CountBy(fn, list);
		}

		public static dynamic CountBy(dynamic fn, RamdaPlaceholder list = null) {
			return Currying.CountBy(fn, list);
		}

		public static dynamic CountBy<TSource>(dynamic fn, IList<TSource> list) {
			return Currying.CountBy(fn, list);
		}

		public static dynamic CountBy(RamdaPlaceholder fn = null, RamdaPlaceholder list = null) {
			return Currying.CountBy(fn, list);
		}
	}
}