// <autogenerated>
//   This file was generated by T4 code generator Dec.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Dec(double n) {
			return Currying.Dec(n);
		}
	}
}