// <autogenerated>
//   This file was generated by T4 code generator DifferenceWith.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic DifferenceWith<TValue>(IList<TValue> list1, IList<TValue> list2) {
			return Currying.DifferenceWith(list1, list2);
		}
		
		public static dynamic DifferenceWith<TValue>(RamdaPlaceholder list1, IList<TValue> list2) {
			return Currying.DifferenceWith(list1, list2); 
		}
		
		public static dynamic DifferenceWith<TValue>(IList<TValue> list1, RamdaPlaceholder list2 = null) {
			return Currying.DifferenceWith(list1, list2); 
		}
		
		public static dynamic DifferenceWith<TValue>(RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.DifferenceWith(list1, list2);
		}
	}
}