// <autogenerated>
//   This file was generated by T4 code generator Divide.int.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Divides two numbers. Equivalent to `a / b`.
		/// <para />
		/// sig: Number -> Number -> Number
		/// </summary>
		/// <param name="a">The first value.</param>
		/// <param name="b">The second value.</param>
		/// <returns>The result of `a / b`.</returns>
		/// <see cref="R.Multiply"/>
		public static dynamic Divide(int a, int b) {
			return Currying.Divide(a, b);
		}

		/// <summary>
		/// Divides two numbers. Equivalent to `a / b`.
		/// <para />
		/// sig: Number -> Number -> Number
		/// </summary>
		/// <param name="a">The first value.</param>
		/// <param name="b">The second value.</param>
		/// <returns>The result of `a / b`.</returns>
		/// <see cref="R.Multiply"/>
		public static dynamic Divide(RamdaPlaceholder a, int b) {
			return Currying.Divide(a, b);
		}

		/// <summary>
		/// Divides two numbers. Equivalent to `a / b`.
		/// <para />
		/// sig: Number -> Number -> Number
		/// </summary>
		/// <param name="a">The first value.</param>
		/// <param name="b">The second value.</param>
		/// <returns>The result of `a / b`.</returns>
		/// <see cref="R.Multiply"/>
		public static dynamic Divide(int a, RamdaPlaceholder b = null) {
			return Currying.Divide(a, b);
		}
	}
}