// <autogenerated>
//   This file was generated by T4 code generator DropLastWhile.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic DropLastWhile<TSource>(Func<TSource, bool> fn, IList<TSource> list) {
			return Currying.DropLastWhile(Delegate(fn), list);
		}

		public static dynamic DropLastWhile<TSource>(RamdaPlaceholder fn, IList<TSource> list) {
			return Currying.DropLastWhile(fn, list);
		}

		public static dynamic DropLastWhile<TSource>(Func<TSource, bool> fn, RamdaPlaceholder list = null) {
			return Currying.DropLastWhile(Delegate(fn), list);
		}

		public static dynamic DropLastWhile(dynamic fn, RamdaPlaceholder list = null) {
			return Currying.DropLastWhile(fn, list);
		}

		public static dynamic DropLastWhile<TSource>(dynamic fn, IList<TSource> list) {
			return Currying.DropLastWhile(fn, list);
		}

		public static dynamic DropLastWhile(RamdaPlaceholder fn = null, RamdaPlaceholder list = null) {
			return Currying.DropLastWhile(fn, list);
		}
	}
}