// <autogenerated>
//   This file was generated by T4 code generator FindLast.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic FindLast<TValue>(Func<TValue, bool> fn, IList<TValue> list) {
			return Currying.FindLast(fn, list);
		}
		
		public static dynamic FindLast<TValue>(RamdaPlaceholder fn, IList<TValue> list) {
			return Currying.FindLast(fn, list); 
		}
		
		public static dynamic FindLast<TValue>(Func<TValue, bool> fn, RamdaPlaceholder list = null) {
			return Currying.FindLast(fn, list); 
		}
		
		public static dynamic FindLast<TValue>(RamdaPlaceholder fn = null, RamdaPlaceholder list = null) {
			return Currying.FindLast(fn, list);
		}
	}
}