// <autogenerated>
//   This file was generated by T4 code generator Flatten.dictionary.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Returns a new list by pulling every item out of it (and all its sub-arrays)and putting them in a new array, depth-first.
		/// <para />
		/// sig: [a] -> [b]
		/// </summary>
		/// <param name="list">The array to consider.</param>
		/// <returns>The flattened list.</returns>
		/// <see cref="R.Unnest"/>
		public static dynamic Flatten(IDictionary list) {
			return Currying.Flatten(list);
		}
	}
}