// <autogenerated>
//   This file was generated by T4 code generator GroupBy.transformer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic GroupBy<TSource>(Func<TSource, string> fn, ITransformer list) {
			return Currying.GroupBy(Delegate(fn), list);
		}

		public static dynamic GroupBy(RamdaPlaceholder fn, ITransformer list) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy(dynamic fn, ITransformer list) {
			return Currying.GroupBy(Delegate(fn), list);
		}
	}
}