// <autogenerated>
//   This file was generated by T4 code generator GroupBy.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic GroupBy<TSource>(Func<TSource, string> fn, IList<TSource> list) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy<TSource>(RamdaPlaceholder fn, IList<TSource> list) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy<TSource>(Func<TSource, string> fn, RamdaPlaceholder list = null) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy(dynamic fn, RamdaPlaceholder list = null) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy<TSource>(dynamic fn, IList<TSource> list) {
			return Currying.GroupBy(fn, list);
		}

		public static dynamic GroupBy(RamdaPlaceholder fn = null, RamdaPlaceholder list = null) {
			return Currying.GroupBy(fn, list);
		}
	}
}