// <autogenerated>
//   This file was generated by T4 code generator Head.string.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Returns the first element of the given list or string. In some librariesthis function is named `first`.
		/// <para />
		/// sig: [a] -> a | Undefined
		/// </summary>
		/// <param name="list">first</param>
		/// <returns>*</returns>
		/// <see cref="R.Tail"/>
		/// <see cref="R.Init"/>
		/// <see cref="R.Last"/>
		public static dynamic Head(string list) {
			return Currying.Head(list);
		}
	}
}