// <autogenerated>
//   This file was generated by T4 code generator Identity.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// A function that does nothing but return the parameter supplied to it. Goodas a default or placeholder function.
		/// <para />
		/// sig: a -> a
		/// </summary>
		/// <param name="x">The value to return.</param>
		/// <returns>The input value, `x`.</returns>
		public static dynamic Identity<TTarget>(TTarget x) {
			return Currying.Identity(x);
		}

		/// <summary>
		/// A function that does nothing but return the parameter supplied to it. Goodas a default or placeholder function.
		/// <para />
		/// sig: a -> a
		/// </summary>
		/// <param name="x">The value to return.</param>
		/// <returns>The input value, `x`.</returns>
		public static dynamic Identity(RamdaPlaceholder x = null) {
			return Currying.Identity(x);
		}
	}
}