// <autogenerated>
//   This file was generated by T4 code generator IndexBy.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic IndexBy<TSource>(Func<TSource, string> fn, IList<TSource> array) {
			return Currying.IndexBy(new DelegateDecorator(fn), array);
		}

		public static dynamic IndexBy<TSource>(RamdaPlaceholder fn, IList<TSource> array) {
			return Currying.IndexBy(fn, array);
		}

		public static dynamic IndexBy<TSource>(Func<TSource, string> fn, RamdaPlaceholder array = null) {
			return Currying.IndexBy(new DelegateDecorator(fn), array);
		}

		public static dynamic IndexBy(dynamic fn, RamdaPlaceholder array = null) {
			return Currying.IndexBy(fn, array);
		}

		public static dynamic IndexBy<TSource>(dynamic fn, IList<TSource> array) {
			return Currying.IndexBy(fn, array);
		}

		public static dynamic IndexBy(RamdaPlaceholder fn = null, RamdaPlaceholder array = null) {
			return Currying.IndexBy(fn, array);
		}
	}
}