// <autogenerated>
//   This file was generated by T4 code generator IndexOf.object.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic IndexOf(object target, object array) {
			return Currying.IndexOf(target, array);
		}

		public static dynamic IndexOf(RamdaPlaceholder target, object array) {
			return Currying.IndexOf(target, array);
		}

		public static dynamic IndexOf(object target, RamdaPlaceholder array = null) {
			return Currying.IndexOf(target, array);
		}
	}
}