// <autogenerated>
//   This file was generated by T4 code generator Intersperse.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Intersperse<TValue, TSeperator>(TSeperator separator, IList<TValue> list) {
			return Currying.Intersperse(separator, list);
		}
		
		public static dynamic Intersperse<TValue, TSeperator>(RamdaPlaceholder separator, IList<TValue> list) {
			return Currying.Intersperse(separator, list); 
		}
		
		public static dynamic Intersperse<TValue, TSeperator>(TSeperator separator, RamdaPlaceholder list = null) {
			return Currying.Intersperse(separator, list); 
		}
		
		public static dynamic Intersperse<TValue, TSeperator>(RamdaPlaceholder separator = null, RamdaPlaceholder list = null) {
			return Currying.Intersperse(separator, list);
		}
	}
}