// <autogenerated>
//   This file was generated by T4 code generator IntersectionWith.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic IntersectionWith<TSource>(Func<TSource, TSource, bool> pred, IList<TSource> list1, IList<TSource> list2) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(RamdaPlaceholder pred, IList<TSource> list1, IList<TSource> list2) {
			return Currying.IntersectionWith(pred, list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(Func<TSource, TSource, bool> pred, RamdaPlaceholder list1, IList<TSource> list2) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(Func<TSource, TSource, bool> pred, IList<TSource> list1, RamdaPlaceholder list2 = null) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(Func<TSource, TSource, bool> pred, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(dynamic pred, RamdaPlaceholder list1, IList<TSource> list2) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(dynamic pred, IList<TSource> list1, RamdaPlaceholder list2 = null) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith(dynamic pred, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith<TSource>(dynamic pred, IList<TSource> list1, IList<TSource> list2) {
			return Currying.IntersectionWith(Delegate(pred), list1, list2);
		}

		public static dynamic IntersectionWith(RamdaPlaceholder pred = null, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.IntersectionWith(pred, list1, list2);
		}
	}
}