// <autogenerated>
//   This file was generated by T4 code generator InvertObj.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic InvertObj<TTarget>(TTarget obj) {
			return Currying.InvertObj(obj);
		}

		public static dynamic InvertObj(RamdaPlaceholder obj = null) {
			return Currying.InvertObj(obj);
		}
	}
}