// <autogenerated>
//   This file was generated by T4 code generator KeysIn.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Returns a list containing the names of all the properties of the suppliedobject, including prototype properties.Note that the order of the output array is not guaranteed to be consistentacross different JS platforms.
		/// <para />
		/// sig: {k: v} -> [k]
		/// </summary>
		/// <param name="obj">The object to extract properties from</param>
		/// <returns>An array of the object's own and prototype properties.</returns>
		public static dynamic KeysIn<TTarget>(TTarget obj) {
			return Currying.KeysIn(obj);
		}

		/// <summary>
		/// Returns a list containing the names of all the properties of the suppliedobject, including prototype properties.Note that the order of the output array is not guaranteed to be consistentacross different JS platforms.
		/// <para />
		/// sig: {k: v} -> [k]
		/// </summary>
		/// <param name="obj">The object to extract properties from</param>
		/// <returns>An array of the object's own and prototype properties.</returns>
		public static dynamic KeysIn(RamdaPlaceholder obj = null) {
			return Currying.KeysIn(obj);
		}
	}
}