// <autogenerated>
//   This file was generated by T4 code generator LensIndex.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic LensIndex(int n) {
			return Currying.LensIndex(n);
		}

		public static dynamic LensIndex(RamdaPlaceholder n = null) {
			return Currying.LensIndex(n);
		}
	}
}