// <autogenerated>
//   This file was generated by T4 code generator Lt.string.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Lt(string a, string b) {
			return Currying.Lt(a, b);
		}

		public static dynamic Lt(RamdaPlaceholder a, string b) {
			return Currying.Lt(a, b);
		}

		public static dynamic Lt(string a, RamdaPlaceholder b = null) {
			return Currying.Lt(a, b);
		}
	}
}