// <autogenerated>
//   This file was generated by T4 code generator Max.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Max(double a, double b) {
			return Currying.Max(a, b);
		}

		public static dynamic Max(RamdaPlaceholder a, double b) {
			return Currying.Max(a, b);
		}

		public static dynamic Max(double a, RamdaPlaceholder b = null) {
			return Currying.Max(a, b);
		}
	}
}