// <autogenerated>
//   This file was generated by T4 code generator Mean.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Mean(IList<double> list) {
			return Currying.Mean(list);
		}

		public static dynamic Mean(RamdaPlaceholder list = null) {
			return Currying.Mean(list);
		}
	}
}