// <autogenerated>
//   This file was generated by T4 code generator Merge.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Merge<TSource1, TSource2>(TSource1 l, TSource2 r) {
			return Currying.Merge(l, r);
		}

		public static dynamic Merge<TSource2>(RamdaPlaceholder l, TSource2 r) {
			return Currying.Merge(l, r);
		}

		public static dynamic Merge<TSource1>(TSource1 l, RamdaPlaceholder r = null) {
			return Currying.Merge(l, r);
		}

		public static dynamic Merge(RamdaPlaceholder l = null, RamdaPlaceholder r = null) {
			return Currying.Merge(l, r);
		}
	}
}