// <autogenerated>
//   This file was generated by T4 code generator MergeAll.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Merges a list of objects together into one object.
		/// <para />
		/// sig: [{k: v}] -> {k: v}
		/// </summary>
		/// <param name="list">An array of objects</param>
		/// <returns>A merged object.</returns>
		/// <see cref="R.Reduce"/>
		public static dynamic MergeAll<TSource>(IList<TSource> list) {
			return Currying.MergeAll(list);
		}

		/// <summary>
		/// Merges a list of objects together into one object.
		/// <para />
		/// sig: [{k: v}] -> {k: v}
		/// </summary>
		/// <param name="list">An array of objects</param>
		/// <returns>A merged object.</returns>
		/// <see cref="R.Reduce"/>
		public static dynamic MergeAll(RamdaPlaceholder list = null) {
			return Currying.MergeAll(list);
		}
	}
}