// <autogenerated>
//   This file was generated by T4 code generator Multiply.int.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Multiply(int a, int b) {
			return Currying.Multiply(a, b);
		}

		public static dynamic Multiply(RamdaPlaceholder a, int b) {
			return Currying.Multiply(a, b);
		}

		public static dynamic Multiply(int a, RamdaPlaceholder b = null) {
			return Currying.Multiply(a, b);
		}
	}
}