// <autogenerated>
//   This file was generated by T4 code generator Negate.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Negate(double n) {
			return Currying.Negate(n);
		}
		
		public static dynamic Negate(RamdaPlaceholder n = null) {
			return Currying.Negate(n); 
		}
	}
}