// <autogenerated>
//   This file was generated by T4 code generator Negate.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Negates its argument.
		/// <para />
		/// sig: Number -> Number
		/// </summary>
		/// <param name="n">first</param>
		/// <returns>Number</returns>
		public static dynamic Negate(double n) {
			return Currying.Negate(n);
		}

		/// <summary>
		/// Negates its argument.
		/// <para />
		/// sig: Number -> Number
		/// </summary>
		/// <param name="n">first</param>
		/// <returns>Number</returns>
		public static dynamic Negate(RamdaPlaceholder n = null) {
			return Currying.Negate(n);
		}
	}
}