// <autogenerated>
//   This file was generated by T4 code generator Not.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Not(bool a) {
			return Currying.Not(a);
		}

		public static dynamic Not(RamdaPlaceholder a = null) {
			return Currying.Not(a);
		}
	}
}