// <autogenerated>
//   This file was generated by T4 code generator Of.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Of<TSource>(TSource x) {
			return Currying.Of(x);
		}
		
		public static dynamic Of<TSource>(RamdaPlaceholder x = null) {
			return Currying.Of(x); 
		}
	}
}