// <autogenerated>
//   This file was generated by T4 code generator Or.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Or(bool a, bool b) {
			return Currying.Or(a, b);
		}

		public static dynamic Or(RamdaPlaceholder a, bool b) {
			return Currying.Or(a, b);
		}

		public static dynamic Or(bool a, RamdaPlaceholder b = null) {
			return Currying.Or(a, b);
		}

		public static dynamic Or(RamdaPlaceholder a = null, RamdaPlaceholder b = null) {
			return Currying.Or(a, b);
		}
	}
}