// <autogenerated>
//   This file was generated by T4 code generator Pair.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Pair<TSource1, TSource2>(TSource1 fst, TSource2 snd) {
			return Currying.Pair(fst, snd);
		}

		public static dynamic Pair<TSource2>(RamdaPlaceholder fst, TSource2 snd) {
			return Currying.Pair(fst, snd);
		}

		public static dynamic Pair<TSource1>(TSource1 fst, RamdaPlaceholder snd = null) {
			return Currying.Pair(fst, snd);
		}

		public static dynamic Pair(RamdaPlaceholder fst = null, RamdaPlaceholder snd = null) {
			return Currying.Pair(fst, snd);
		}
	}
}