// <autogenerated>
//   This file was generated by T4 code generator PathOr.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic PathOr<TValue, TTarget>(TValue d, IList<string> p, TTarget obj) {
			return Currying.PathOr(d, p, obj);
		}

		public static dynamic PathOr<TTarget>(RamdaPlaceholder d, IList<string> p, TTarget obj) {
			return Currying.PathOr(d, p, obj);
		}

		public static dynamic PathOr<TValue, TTarget>(TValue d, RamdaPlaceholder p, TTarget obj) {
			return Currying.PathOr(d, p, obj);
		}

		public static dynamic PathOr<TValue>(TValue d, IList<string> p, RamdaPlaceholder obj = null) {
			return Currying.PathOr(d, p, obj);
		}

		public static dynamic PathOr<TValue>(TValue d, RamdaPlaceholder p = null, RamdaPlaceholder obj = null) {
			return Currying.PathOr(d, p, obj);
		}

		public static dynamic PathOr(RamdaPlaceholder d = null, RamdaPlaceholder p = null, RamdaPlaceholder obj = null) {
			return Currying.PathOr(d, p, obj);
		}
	}
}