// <autogenerated>
//   This file was generated by T4 code generator PathEq.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic PathEq<TValue, TTarget>(IList<object> path, TValue val, TTarget obj) {
			return Currying.PathEq(path, val, obj);
		}

		public static dynamic PathEq<TValue, TTarget>(RamdaPlaceholder path, TValue val, TTarget obj) {
			return Currying.PathEq(path, val, obj);
		}

		public static dynamic PathEq<TTarget>(IList<object> path, RamdaPlaceholder val, TTarget obj) {
			return Currying.PathEq(path, val, obj);
		}

		public static dynamic PathEq<TValue>(IList<object> path, TValue val, RamdaPlaceholder obj = null) {
			return Currying.PathEq(path, val, obj);
		}

		public static dynamic PathEq(IList<object> path, RamdaPlaceholder val = null, RamdaPlaceholder obj = null) {
			return Currying.PathEq(path, val, obj);
		}

		public static dynamic PathEq(RamdaPlaceholder path = null, RamdaPlaceholder val = null, RamdaPlaceholder obj = null) {
			return Currying.PathEq(path, val, obj);
		}
	}
}