// <autogenerated>
//   This file was generated by T4 code generator PickAll.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic PickAll<TTarget>(IList<string> names, TTarget obj) {
			return Currying.PickAll(names, obj);
		}

		public static dynamic PickAll<TTarget>(RamdaPlaceholder names, TTarget obj) {
			return Currying.PickAll(names, obj);
		}

		public static dynamic PickAll(IList<string> names, RamdaPlaceholder obj = null) {
			return Currying.PickAll(names, obj);
		}

		public static dynamic PickAll(RamdaPlaceholder names = null, RamdaPlaceholder obj = null) {
			return Currying.PickAll(names, obj);
		}
	}
}