// <autogenerated>
//   This file was generated by T4 code generator Project.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Project<TSource>(IList<string> props, IList<TSource> objs) {
			return Currying.Project(props, objs);
		}

		public static dynamic Project<TSource>(RamdaPlaceholder props, IList<TSource> objs) {
			return Currying.Project(props, objs);
		}

		public static dynamic Project(IList<string> props, RamdaPlaceholder objs = null) {
			return Currying.Project(props, objs);
		}

		public static dynamic Project(RamdaPlaceholder props = null, RamdaPlaceholder objs = null) {
			return Currying.Project(props, objs);
		}
	}
}