// <autogenerated>
//   This file was generated by T4 code generator Props.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Props<TTarget>(IEnumerable<string> ps, TTarget obj) {
			return Currying.Props(ps, obj);
		}
		
		public static dynamic Props<TTarget>(RamdaPlaceholder ps, TTarget obj) {
			return Currying.Props(ps, obj); 
		}
		
		public static dynamic Props<TTarget>(IEnumerable<string> ps, RamdaPlaceholder obj = null) {
			return Currying.Props(ps, obj); 
		}
		
		public static dynamic Props<TTarget>(RamdaPlaceholder ps = null, RamdaPlaceholder obj = null) {
			return Currying.Props(ps, obj);
		}
	}
}