// <autogenerated>
//   This file was generated by T4 code generator Reduced.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Returns a value wrapped to indicate that it is the final value of the reduceand transduce functions. The returned value should be considered a blackbox: the internal structure is not guaranteed to be stable.Note: this optimization is unavailable to functions not explicitly listedabove. For instance, it is not currently supported by reduceRight.
		/// <para />
		/// sig: a -> *
		/// </summary>
		/// <param name="x">The final value of the reduce.</param>
		/// <returns>The wrapped value.</returns>
		/// <see cref="R.Reduce"/>
		/// <see cref="R.Transduce"/>
		public static dynamic Reduced<TTarget>(TTarget x) {
			return Currying.Reduced(x);
		}

		/// <summary>
		/// Returns a value wrapped to indicate that it is the final value of the reduceand transduce functions. The returned value should be considered a blackbox: the internal structure is not guaranteed to be stable.Note: this optimization is unavailable to functions not explicitly listedabove. For instance, it is not currently supported by reduceRight.
		/// <para />
		/// sig: a -> *
		/// </summary>
		/// <param name="x">The final value of the reduce.</param>
		/// <returns>The wrapped value.</returns>
		/// <see cref="R.Reduce"/>
		/// <see cref="R.Transduce"/>
		public static dynamic Reduced(RamdaPlaceholder x = null) {
			return Currying.Reduced(x);
		}
	}
}