// <autogenerated>
//   This file was generated by T4 code generator Reject.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Reject<TTarget, TArg>(Func<TArg, bool> pred, TTarget filterable) {
			return Currying.Reject(Delegate(pred), filterable);
		}

		public static dynamic Reject<TTarget>(RamdaPlaceholder pred, TTarget filterable) {
			return Currying.Reject(pred, filterable);
		}

		public static dynamic Reject<TArg>(Func<TArg, bool> pred, RamdaPlaceholder filterable = null) {
			return Currying.Reject(Delegate(pred), filterable);
		}

		public static dynamic Reject(dynamic pred, RamdaPlaceholder filterable = null) {
			return Currying.Reject(pred, filterable);
		}

		public static dynamic Reject<TTarget>(dynamic pred, TTarget filterable) {
			return Currying.Reject(pred, filterable);
		}

		public static dynamic Reject(RamdaPlaceholder pred = null, RamdaPlaceholder filterable = null) {
			return Currying.Reject(pred, filterable);
		}
	}
}