// <autogenerated>
//   This file was generated by T4 code generator Reverse.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Returns a new list or string with the elements or characters in reverseorder.
		/// <para />
		/// sig: [a] -> [a]
		/// </summary>
		/// <param name="list">first</param>
		/// <returns>*</returns>
		public static dynamic Reverse<TSource>(IEnumerable<TSource> list) {
			return Currying.Reverse(list);
		}

		/// <summary>
		/// Returns a new list or string with the elements or characters in reverseorder.
		/// <para />
		/// sig: [a] -> [a]
		/// </summary>
		/// <param name="list">first</param>
		/// <returns>*</returns>
		public static dynamic Reverse(RamdaPlaceholder list = null) {
			return Currying.Reverse(list);
		}
	}
}