// <autogenerated>
//   This file was generated by T4 code generator Reverse.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Reverse<TSource>(IEnumerable<TSource> list) {
			return Currying.Reverse(list);
		}

		public static dynamic Reverse(RamdaPlaceholder list = null) {
			return Currying.Reverse(list);
		}
	}
}