// <autogenerated>
//   This file was generated by T4 code generator Sequence.list.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence<TSource>(Delegate of, IList<TSource> traversable) {
			return Currying.Sequence(Delegate(of), traversable);
		}

		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence<TSource>(RamdaPlaceholder of, IList<TSource> traversable) {
			return Currying.Sequence(of, traversable);
		}

		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence(Delegate of, RamdaPlaceholder traversable = null) {
			return Currying.Sequence(Delegate(of), traversable);
		}

		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence(dynamic of, RamdaPlaceholder traversable = null) {
			return Currying.Sequence(Delegate(of), traversable);
		}

		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence<TSource>(dynamic of, IList<TSource> traversable) {
			return Currying.Sequence(Delegate(of), traversable);
		}

		/// <summary>
		/// Transforms a [Traversable](https://github.com/fantasyland/fantasy-land#traversable)of [Applicative](https://github.com/fantasyland/fantasy-land#applicative) into anApplicative of Traversable.Dispatches to the `sequence` method of the second argument, if present.
		/// <para />
		/// sig: (Applicative f, Traversable t) => (a -> f a) -> t (f a) -> f (t a)
		/// </summary>
		/// <param name="of">first</param>
		/// <param name="traversable">second</param>
		/// <returns>*</returns>
		/// <see cref="R.Traverse"/>
		public static dynamic Sequence(RamdaPlaceholder of = null, RamdaPlaceholder traversable = null) {
			return Currying.Sequence(of, traversable);
		}
	}
}