// <autogenerated>
//   This file was generated by T4 code generator SplitEvery.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic SplitEvery<TValue>(int n, IList<TValue> list) {
			return Currying.SplitEvery(n, list);
		}
		
		public static dynamic SplitEvery<TValue>(RamdaPlaceholder n, IList<TValue> list) {
			return Currying.SplitEvery(n, list); 
		}
		
		public static dynamic SplitEvery<TValue>(int n, RamdaPlaceholder list = null) {
			return Currying.SplitEvery(n, list); 
		}
		
		public static dynamic SplitEvery<TValue>(RamdaPlaceholder n = null, RamdaPlaceholder list = null) {
			return Currying.SplitEvery(n, list);
		}
	}
}