// <autogenerated>
//   This file was generated by T4 code generator Sum.double.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Adds together all the elements of a list.
		/// <para />
		/// sig: [Number] -> Number
		/// </summary>
		/// <param name="list">An array of numbers</param>
		/// <returns>The sum of all the numbers in the list.</returns>
		/// <see cref="R.Reduce"/>
		public static dynamic Sum(IList<double> list) {
			return Currying.Sum(list);
		}

		/// <summary>
		/// Adds together all the elements of a list.
		/// <para />
		/// sig: [Number] -> Number
		/// </summary>
		/// <param name="list">An array of numbers</param>
		/// <returns>The sum of all the numbers in the list.</returns>
		/// <see cref="R.Reduce"/>
		public static dynamic Sum(RamdaPlaceholder list = null) {
			return Currying.Sum(list);
		}
	}
}