// <autogenerated>
//   This file was generated by T4 code generator SymmetricDifferenceWith.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(Func<TSource1, TSource2, bool> pred, IList<TSource1> list1, IList<TSource2> list2) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(RamdaPlaceholder pred, IList<TSource1> list1, IList<TSource2> list2) {
			return Currying.SymmetricDifferenceWith(pred, list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(Func<TSource1, TSource2, bool> pred, RamdaPlaceholder list1, IList<TSource2> list2) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(Func<TSource1, TSource2, bool> pred, IList<TSource1> list1, RamdaPlaceholder list2 = null) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(Func<TSource1, TSource2, bool> pred, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource2>(dynamic pred, RamdaPlaceholder list1, IList<TSource2> list2) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1>(dynamic pred, IList<TSource1> list1, RamdaPlaceholder list2 = null) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith(dynamic pred, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith<TSource1, TSource2>(dynamic pred, IList<TSource1> list1, IList<TSource2> list2) {
			return Currying.SymmetricDifferenceWith(Delegate(pred), list1, list2);
		}

		public static dynamic SymmetricDifferenceWith(RamdaPlaceholder pred = null, RamdaPlaceholder list1 = null, RamdaPlaceholder list2 = null) {
			return Currying.SymmetricDifferenceWith(pred, list1, list2);
		}
	}
}