// <autogenerated>
//   This file was generated by T4 code generator TakeLastWhile.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic TakeLastWhile<TSource>(Func<TSource, bool> fn, IList<TSource> list) {
			return Currying.TakeLastWhile(fn, list);
		}

		public static dynamic TakeLastWhile<TSource>(RamdaPlaceholder fn, IList<TSource> list) {
			return Currying.TakeLastWhile(fn, list);
		}

		public static dynamic TakeLastWhile<TSource>(Func<TSource, bool> fn, RamdaPlaceholder list = null) {
			return Currying.TakeLastWhile(fn, list);
		}

		public static dynamic TakeLastWhile(RamdaPlaceholder fn = null, RamdaPlaceholder list = null) {
			return Currying.TakeLastWhile(fn, list);
		}
	}
}