// <autogenerated>
//   This file was generated by T4 code generator ToLower.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic ToLower(string str) {
			return Currying.ToLower(str);
		}

		public static dynamic ToLower(RamdaPlaceholder str = null) {
			return Currying.ToLower(str);
		}
	}
}