// <autogenerated>
//   This file was generated by T4 code generator ToUpper.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// The upper case version of a string.
		/// <para />
		/// sig: String -> String
		/// </summary>
		/// <param name="str">The string to upper case.</param>
		/// <returns>The upper case version of `str`.</returns>
		/// <see cref="R.ToLower"/>
		public static dynamic ToUpper(string str) {
			return Currying.ToUpper(str);
		}

		/// <summary>
		/// The upper case version of a string.
		/// <para />
		/// sig: String -> String
		/// </summary>
		/// <param name="str">The string to upper case.</param>
		/// <returns>The upper case version of `str`.</returns>
		/// <see cref="R.ToLower"/>
		public static dynamic ToUpper(RamdaPlaceholder str = null) {
			return Currying.ToUpper(str);
		}
	}
}