// <autogenerated>
//   This file was generated by T4 code generator Transpose.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Transpose<TArg>(TArg[][] list) {
			return Currying.Transpose(list);
		}
			
		public static dynamic Transpose<TArg>(RamdaPlaceholder list = null) {
			return Currying.Transpose(list);
		}
	}
}