// <autogenerated>
//   This file was generated by T4 code generator Union.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Union<TSource>(IList<TSource> @as, IList<TSource> bs) {
			return Currying.Union(@as, bs);
		}

		public static dynamic Union<TSource>(RamdaPlaceholder @as, IList<TSource> bs) {
			return Currying.Union(@as, bs);
		}

		public static dynamic Union<TSource>(IList<TSource> @as, RamdaPlaceholder bs = null) {
			return Currying.Union(@as, bs);
		}

		public static dynamic Union(RamdaPlaceholder @as = null, RamdaPlaceholder bs = null) {
			return Currying.Union(@as, bs);
		}
	}
}