// <autogenerated>
//   This file was generated by T4 code generator Unnest.object.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using System.Threading.Tasks;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		/// <summary>
		/// Shorthand for `R.chain(R.identity)`, which removes one level of nesting fromany [Chain](https://github.com/fantasyland/fantasy-land#chain).
		/// <para />
		/// sig: Chain c => c (c a) -> c a
		/// </summary>
		/// <param name="list">first</param>
		/// <returns>*</returns>
		/// <see cref="R.Flatten"/>
		/// <see cref="R.Chain"/>
		public static dynamic Unnest(object list) {
			return Currying.Unnest(list);
		}
	}
}