// <autogenerated>
//   This file was generated by T4 code generator Update.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Update<TSource>(int idx, TSource x, IList<TSource> list) {
			return Currying.Update(idx, x, list);
		}

		public static dynamic Update<TSource>(RamdaPlaceholder idx, TSource x, IList<TSource> list) {
			return Currying.Update(idx, x, list);
		}

		public static dynamic Update<TSource>(int idx, RamdaPlaceholder x, IList<TSource> list) {
			return Currying.Update(idx, x, list);
		}

		public static dynamic Update<TSource>(int idx, TSource x, RamdaPlaceholder list = null) {
			return Currying.Update(idx, x, list);
		}

		public static dynamic Update(int idx, RamdaPlaceholder x = null, RamdaPlaceholder list = null) {
			return Currying.Update(idx, x, list);
		}

		public static dynamic Update(RamdaPlaceholder idx = null, RamdaPlaceholder x = null, RamdaPlaceholder list = null) {
			return Currying.Update(idx, x, list);
		}
	}
}