// <autogenerated>
//   This file was generated by T4 code generator View.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic View<TTarget>(Func<Func<TTarget, IdentityObj>, Func<TTarget, IdentityObj>> lens, TTarget x) {
			return Currying.View(lens, x);
		}
			
		public static dynamic View<TTarget>(RamdaPlaceholder lens, TTarget x) {
			return Currying.View(lens, x);
		}

		public static dynamic View<TTarget>(dynamic lens, TTarget x) {
			return Currying.View(lens, x); 
		}
					
		public static dynamic View(dynamic lens, RamdaPlaceholder x = null) {
			return Currying.View(lens, x);
		}
			
		public static dynamic View<TTarget>(Func<Func<TTarget, IdentityObj>, Func<TTarget, IdentityObj>> lens, RamdaPlaceholder x = null) {
			return Currying.View(lens, x);
		}
		
		public static dynamic View<TTarget>(RamdaPlaceholder lens = null, RamdaPlaceholder x = null) {
			return Currying.View(lens, x);
		}
	}
}