// <autogenerated>
//   This file was generated by T4 code generator When.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic When<TArg, TReturn>(Func<TArg, bool> pred, Func<TArg, TReturn> whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x);
		}

		public static dynamic When<TArg>(dynamic pred, dynamic whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x); 
		}
					
		public static dynamic When<TArg>(RamdaPlaceholder pred, dynamic whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x);
		}
			
		public static dynamic When<TArg, TReturn>(RamdaPlaceholder pred, Func<TArg, TReturn> whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x);
		}
					
		public static dynamic When<TArg>(dynamic pred, RamdaPlaceholder whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x);
		}
			
		public static dynamic When<TArg, TReturn>(Func<TArg, bool> pred, RamdaPlaceholder whenTrueFn, TArg x) {
			return Currying.When(pred, whenTrueFn, x);
		}
					
		public static dynamic When<TArg, TReturn>(dynamic pred, Func<TArg, TReturn> whenTrueFn, RamdaPlaceholder x = null) {
			return Currying.When(pred, whenTrueFn, x);
		}
					
		public static dynamic When<TArg>(Func<TArg, bool> pred, dynamic whenTrueFn, RamdaPlaceholder x = null) {
			return Currying.When(pred, whenTrueFn, x);
		}
			
		public static dynamic When<TArg, TReturn>(Func<TArg, bool> pred, Func<TArg, TReturn> whenTrueFn, RamdaPlaceholder x = null) {
			return Currying.When(pred, whenTrueFn, x);
		}
		
		public static dynamic When<TArg, TReturn>(Func<TArg, bool> pred, RamdaPlaceholder whenTrueFn = null, RamdaPlaceholder x = null) {
			return Currying.When(pred, whenTrueFn, x);
		}
		
		public static dynamic When<TArg, TReturn>(RamdaPlaceholder pred = null, RamdaPlaceholder whenTrueFn = null, RamdaPlaceholder x = null) {
			return Currying.When(pred, whenTrueFn, x);
		}
	}
}