// <autogenerated>
//   This file was generated by T4 code generator Where.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Dynamic;
using System.Collections;
using static Ramda.NET.Currying;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace Ramda.NET
{
	public static partial class R
	{	
		public static dynamic Where<TTarget>(IDictionary<string, Delegate> spec, TTarget testObj) {
			return Currying.Where(spec, testObj);
		}

		public static dynamic Where<TTarget>(RamdaPlaceholder spec, TTarget testObj) {
			return Currying.Where(spec, testObj);
		}

		public static dynamic Where(IDictionary<string, Delegate> spec, RamdaPlaceholder testObj = null) {
			return Currying.Where(spec, testObj);
		}

		public static dynamic Where(RamdaPlaceholder spec = null, RamdaPlaceholder testObj = null) {
			return Currying.Where(spec, testObj);
		}
	}
}